import Head from "next/head";
import SearchBar from "../components/base/SearchBar";
import Navbar from "../components/module/Navbar";
import Footer from "../components/module/Footer";
import Link from "next/link";
import Container from "../components/base/Container";
import Button from "../components/base/Button";
import { getAllRecipes } from "../services/recipes";
import clsx from "clsx";
import { BiChevronLeft, BiChevronRight } from "react-icons/bi";
import { useState } from "react";

export async function getServerSideProps() {
  try {
    const resultPopularRecipes = await getAllRecipes({ limit: 9999 });

    if (!resultPopularRecipes || !resultPopularRecipes.data) {
      throw new Error("Data not found");
    }

    return {
      props: {
        popularRecipes: resultPopularRecipes.data,
      },
    };
  } catch (error) {
    console.error("Failed to fetch popular recipes:", error);
    return {
      props: {
        popularRecipes: [],
        error: "Failed to fetch popular recipes",
      },
    };
  }
}

export default function Home({ popularRecipes }) {
  const [page, setPage] = useState(1);
  const limit = 6;
  const totalPage = Math.ceil(popularRecipes.length / limit);

  const handlePrev = () => {
    if (page > 1) {
      setPage((prev) => prev - 1);
    }
  };

  const handleNext = () => {
    if (page < totalPage) {
      setPage((prev) => prev + 1);
    }
  };

  return (
    <Container>
      <Head>
        <title>Home - Mama Recipe</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>

      <Navbar className={`absolute top-0`} home={true} />

      <Container
        className={`bg-recipe-yellow-light flex justify-between h-screen`}
      >
        <section className=" px-10 sm:px-[135px] w-full my-auto">
          <div
            className={`font-bold text-center md:text-left text-4xl md:text-6xl lg:text-7xl leading-normal lg:leading-[90px] text-recipe-blue w-full lg:w-[800px] mb-10`}
          >
            <h1 className="">Discover Recipe</h1>
            <h1 className="">& Delicious Food</h1>
          </div>

          <SearchBar className={`lg:w-5/6 xl:w-[670px] `} />
        </section>

        <aside className="hidden xl:block w-5/12 relative bg-recipe-yellow-normal">
          <img
            className="absolute min-w-[370px] w-full top-60 2xl:top-20 -left-52 2xl:-left-72 z-50 transition-transform duration-300 ease-in-out"
            src="/assets/group icons/Group 700.png"
            alt="Food Image"
          />
        </aside>
      </Container>

      <Container className={`bg-recipe-yellow-light hidden lg:block`}>
        <section className="py-20 flex flex-col gap-24 xl:gap-48 ">
          <SubTitle className={`px-10 sm:px-[135px] `}>
            Popular For You !
          </SubTitle>

          <PopularForYou />
        </section>
      </Container>

      <Container className={`bg-recipe-yellow-light relative`}>
        <div className="hidden lg:block absolute left-0 bottom-0 2xl:bottom-32 w-1/4 h-2/4 bg-recipe-yellow-normal"></div>
        <section className="px-10 sm:px-[135px] py-20 flex flex-col gap-24 xl:gap-48 ">
          <SubTitle>New Recipe</SubTitle>

          <NewestRecipe recipe={popularRecipes[0]} />
        </section>
      </Container>

      <Container className={`bg-recipe-yellow-light`}>
        <section className="px-10 py-14 sm:px-[135px] flex flex-col gap-24">
          <SubTitle>Popular Recipe</SubTitle>

          <ListPopularRecipe
            recipes={popularRecipes}
            page={page}
            limit={limit}
          />
          <div className="w-full flex justify-center items-center gap-1 sm:gap-[14px] text-recipe-dark">
            <Button onClick={handlePrev} className={`font-medium text-5xl`}>
              <BiChevronLeft />
            </Button>
            <div className="flex justify-center items-center gap-[14px] font-medium text-4xl text-center">
              <span className="flex justify-center items-center w-[48px] h-[48px]">
                {page}
              </span>
              <span className="flex justify-center items-center w-[48px] h-[48px]">
                to
              </span>
              <span className="flex justify-center items-center w-[48px] h-[48px]">
                {totalPage}
              </span>
            </div>
            <Button onClick={handleNext} className={`font-medium text-5xl`}>
              <BiChevronRight />
            </Button>
          </div>
        </section>
      </Container>

      <Footer />
    </Container>
  );
}

const SubTitle = ({ className, children }) => {
  return (
    <div
      className={clsx("h-36 flex justify-start items-center gap-8", className)}
    >
      <div className="w-[25px] h-full bg-recipe-yellow-normal"></div>
      <h2 className=" font-medium text-5xl text-recipe-dark">{children}</h2>
    </div>
  );
};

const PopularForYou = () => {
  return (
    <div className="flex gap-10">
      <div className="w-1/3 relative">
        <div className="w-full h-full overflow-hidden rounded-[20px]">
          <img
            className="w-full h-full object-cover object-center"
            src="/assets/Rectangle 7.png"
            alt=""
          />
        </div>
        <h2 className="absolute rounded-[15px] bg-[#ffffffd8] p-2 xl:p-4 left-0 bottom-0 m-10 xl:m-[60px] font-medium text-base lg:text-lg xl:text-xl 2xl:text-[42px] leading-10 text-recipe-dark ">
          {`Pizza Lamoa`}
        </h2>
      </div>
      <div className="w-1/3 relative">
        <div className="w-full h-full overflow-hidden rounded-[20px]">
          <img
            className="w-full h-full object-cover object-center"
            src="/assets/Rectangle 8.png"
            alt=""
          />
        </div>
        <h2 className="absolute rounded-[15px] bg-[#ffffffd8] p-2 xl:p-4 left-0 bottom-0 m-10 xl:m-[60px] font-medium text-base lg:text-lg xl:text-xl 2xl:text-[42px] leading-10 text-recipe-dark ">
          {`King Burger`}
        </h2>
      </div>
    </div>
  );
};

const NewestRecipe = ({ recipe }) => {
  const newestRecipe = {
    id: `1`,
    title: `Healthy Bone Broth Ramen (Quick & Easy)`,
    image: `/assets/Rectangle 313.png`,
    description: `Quick + Easy Chicken Bone Broth Ramen-Healthy chicken ramen in a hurry? That’s right!`,
  };
  return (
    <div className="flex flex-col lg:flex-row flex-nowrap justify-between gap-20 xl:gap-40 2xl:gap-60">
      <div className="w-full xl:w-1/2 relative">
        <div className="w-full h-full overflow-hidden rounded-[20px]">
          <img
            className="w-full h-full object-cover object-center"
            src={
              recipe.image && recipe.image.startsWith("https://")
                ? recipe.image
                : `/assets/Rectangle 313.png`
            }
            alt={recipe.title}
          />
        </div>
      </div>
      <div className="mt-0 2xl:mt-20 w-full xl:w-1/2">
        <h1 className="font-medium text-4xl sm:text-[54px] sm:leading-[72px]">
          {recipe.title}
        </h1>
        <div className="w-16 2xl:w-[100px] border-2 border-recipe-yellow-dark mt-6 mb-10"></div>
        <p className="font-base text-2xl leading-8 mb-10">
          {recipe.title} is a brand new and exciting recipe. You should
          definitely check it out!
        </p>
        <Link href={`/recipe/${recipe.id}`}>
          <Button
            className={`px-[50px] py-5 bg-recipe-yellow-normal hover:bg-recipe-yellow-dark text-white font-medium text-base mx-auto`}
          >
            Learn More
          </Button>
        </Link>
      </div>
    </div>
  );
};

const ListPopularRecipe = ({ recipes, page, limit }) => {
  const offset = (page - 1) * limit;
  const displayedRecipes = recipes.slice(offset, offset + limit);

  return (
    <div className="flex flex-wrap justify-around gap-14">
      {displayedRecipes.map((recipe) => (
        <Link
          href={`/recipe/${recipe.id}`}
          key={recipe.id}
          className={`bg-white rounded-[15px] w-full md:w-2/5 lg:w-[28%] xl:w-[29.5%] after:content-[""] after:block after:pb-[100%] relative overflow-hidden`}
        >
          <img
            className=" absolute w-full h-full object-cover object-center hover:scale-105 transition-transform duration-300 ease-in-out"
            src={
              recipe.image && recipe.image.startsWith("https://")
                ? recipe.image
                : `/assets/icons/Default_Recipe_Image.png`
            }
            alt={recipe.title}
          />
          <h2 className="absolute rounded-[15px] bg-[#ffffffd8] p-2 left-0 bottom-0 m-5 md:m-2 xl:m-5 2xl:m-10 font-medium text-base lg:text-lg xl:text-xl 2xl:text-[28px] xl:leading-10 text-recipe-dark ">
            {recipe.title || `Unknown Recipe Name`}
          </h2>
        </Link>
      ))}
    </div>
  );
};
